version: "3.8"

services:
    # db:
    #   image: ankane/pgvector
    #   restart: "no"
    #   environment:
    #     POSTGRES_USER: postgres
    #     POSTGRES_PASSWORD: example
    #     POSTGRES_DB: mydatabase
    #   ports:
    #     - "5432:5432"
    #   volumes:
    #     - ./postgres-data:/var/lib/postgresql/data

    # local-ai:
    #   image: quay.io/go-skynet/local-ai:latest
    #   ports:
    #     - 8080:8080
    #   environment:
    #     MODELS_PATH: /models
    #     GO_TAGS: tts
    #   volumes:
    #     - ./models:/models:cached
    #   restart: "no"

    # nocodb:
    #   image: nocodb/nocodb:latest
    #   restart: "no"
    #   environment:
    #     NC_DB: pg://db:5432?u=postgres&p=example&d=mydatabase
    #   volumes:
    #     - ./nocodb-data:/usr/app/data/
    #   ports:
    #     - 8081:8080

    browserless:
        image: browserless/chrome:latest
        restart: "no"
        environment:
            MAX_CONCURRENT_CONNECTIONS: "10"
        ports:
            - 3000:3000

    jupyter:
        image: quay.io/jupyter/scipy-notebook:latest
        restart: "no"
        ports:
            - 8888:8888
        volumes:
            - ./jupyter-data:/home/jovyan/work
