version: '3.8'

services:
  db:
    image: ankane/pgvector
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  
  local-ai:
    image: quay.io/go-skynet/local-ai:latest
    ports:
      - 8080:8080
    environment:
      MODELS_PATH: /models
      GO_TAGS: tts
    volumes:
      - ./models:/models:cached
    restart: "no"